#' trim_html
#'
#' @param html_doc An html fact page generated by R Markdown
#' @param output_dir A directory ending in / where the trimmed html should be saved
#'
#' @examples trim_html(html_doc = "factsheets/Alabama.html",
#'                     output_dir = "factsheets_clean/")
#'                     
trim_html <- function(html_doc, output_dir) {
  
  html <- scan(html_doc, 
               what = character(), 
               skip = 350,
               sep = "\n",
               blank.lines.skip = FALSE,
               strip.white = TRUE)
  
  start <- which(html == "<!--html_start-->", TRUE)
  end <- which(html == "<!--html_end-->", TRUE) + 2
  
  trimmed_html <- html[start:end]
  
  output_name <- strsplit(
    html_doc,
    split = "/"
  )[[1]][length(strsplit(html_doc, split = "/")[[1]])]
  
  writeLines(trimmed_html, paste0(output_dir, output_name))
  
}
